name: Radio
main: in.nikitapek.radio.RadioPlugin
version: ${project.version}
load: POSTWORLD
author: Indiv0
description: A plugin for simulating radio functionality as initially implemented in CMA.
dev-url: http://github.com/Indiv0/Radio/

commands:
  radio:
    description: Controls all functions of the Radio plugin.
    usage: |
      /<command> [tune|scan|off]
      Example: /<command> tune [frequency] - Sets scan frequency.
      Example: /<command> scan - Scans all broadcasts.
      Example: /<command> off - Turns off the radio.
    permission: radio.radio
    permission-message: Sorry, you don't have permission to use Radio.

permissions:
  radio.*:
    description: Controls all Radio permissions
    children:
      radio.radio: true
