name: Radio
main: in.nikitapek.radio.RadioPlugin
load: POSTWORLD
version: ${project.version}
author: Indiv0
description: A plugin for simulating radio functionality as initially implemented in CMA.
dev-url: http://github.com/Indiv0/Radio/

commands:
  radio:
    description: Controls all functions of the Radio plugin.
    usage: |
      /<command> off - Turns off the radio
      /<command> scan - Scans all broadcasts
      /<command> tune [frequency] - Sets scan frequency

permissions:
  radio.radio.off:
    children:
      radio.radio: true
  radio.radio.scan:
      radio.radio: true
  radio.radio.tune:
      radio.radio: true